version : '3'

services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile_Nginx
    image: 080950/nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 080950/laravelproject
    container_name: app
    restart:  unless-stopped
    volumes: 
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
